### ISSUE TITLE
long sms not sent

### ISSUE THREAD

**Issue by gymka** [anjlab/android-sms-gateway#1]
if sms text is less then 160symbols everything works, but if it's longer sms not sent.(only shown as „sent“)

**Comment by hamzacma** [comment]
hi, is the problem solved? thank.

**Comment by serggl** [comment]
I believe yes fb1bf0126f5fa72f9b82249ed7805c6647da4c7a

**Comment by gymka** [comment]
problem solved, but i don't know how to compile:) and in release version problem not solved

**Comment by hamzacma** [comment]
I have compiled but still does not work. Messages are received by the mobile phone which I have installed the Android SMS Gateway app in. But the said mobile cannot send the messages to destination numbers. It only happens when the length of the messages is more than 160 characters.

Dear developer, it would be great if would come to help us. Thanks a lot.

**Comment by fealXX** [comment]
That is just the way SMS work. Split longer messages.

**Comment by hamzacma** [comment]
When I send messages more than 160 characters using my default messaging app from my mobile phone, it sends without any split and also the recipient receives without any split. Is this possible to send messages containing more than 160 characters without any split. Split messages does not look good. Thanks.

**Comment by fealXX** [comment]
No it is not possible. The effect you are talking about is multipart messaging, which is indeed supported by most smartphones, but still sending multiple sms.
I have a working fix relying on it in my fork.

See here:
http://bit.ly/2hMlpv6

Edit: url fixed

**Comment by hamzacma** [comment]
Can this app send messages directly to the recipients? What happing at the moment is this app is sending messages to the default messaging app and the default app is sending messages to the recipients. 

I send bulk sms from my web app to GCM to Android SMS Gateway to Default messaging app to Destination number. I just want to omit "Default messaging app" from this process. Is this possible? 

Thanks.

**Comment by fealXX** [comment]
The default messaging app is not used in this process, but uses the same SMS-System of your android phone - that is why you are seeing the SMS in your default messaging app. 
I don't know of another way to send sms on android but the SMS-System, so I believe you can't bypass that.

**Comment by hamzacma** [comment]
I am really sorry. I am not a programmer. I have an online shop. I had the idea to send bulk messages from my web app using my mobile phone and SIM card. I did not want to pay any money to the SMS gateway provider as they are costly. It was fine when the character was up to 160. But when the character went more than 160, the app stopped sending messages. I have been googling for a long period of time, I have rooted my phone as well, but did not get any clue to solve the problem. 

I am a bit confused here.  If my default messaging app can send messages more than 160 characters without any split, why this app cannot?

Sorry agin for the trouble.

**Comment by fealXX** [comment]
You're confused about your default app beeing able to send messages with more that 160 characters - that is not possible. It just splits and stitches the messages that are longer for you, something that is not implemented in this app here, hence the errormessage if the message is longer than 160 characters.

**Comment by hamzacma** [comment]
Oh my goodness. Thanks a lot.  Just I got it. Everything is clear to me now. I have googled a lot but I did not get this information before. Is this possible for you to write codes on splitting and stitching the messages so that it works like my default app? It would be a great help for me. Regards.

**Comment by serggl** [comment]
thats weird: I was sure I have committed a fix that allows long text messages. Now its in place.
@hamzacma try to pull and use latest source code

**Comment by fealXX** [comment]
Jep, the newest commit should fix the issue.

**Comment by hamzacma** [comment]
I am sorry it is not working for me. Message sending shows "failed". I have compiled from your updated source code. You have added a new option "Forwarding incoming messages". In your old version - it was not. Am I right? Thanks.
